runtime: python39

handlers:
- url: /
  static_files: public/index.html
  upload: public/index.html

- url: /privacy
  static_files: public/privacy.html
  upload: public/privacy.html

- url: /terms
  static_files: public/terms.html
  upload: public/terms.html

- url: /(.+)
  static_files: public/\1
  upload: public/(.+)
